### ISSUE TITLE
[deposit-form] add 'id' prop to fields component

### ISSUE THREAD

**Issue by rwwalla2** [Grainger-Engineering-Library/3deposit#31]

**Comment by MichaelMassaro** [comment]
Hey, I made a push regarding this but not sure if this is what you meant. I barely made any changes so it seems overly simple. Could you elaborate or send me a link with what you want me to do? (I know you're busy and not here right now.)

**Comment by rwwalla2** [comment]
You need to pass the id value from App.vue to the Fields.vue component. I looked at your change and it is not quite right. Look at how the id gets passed to the FileProgress.vue prop.
