### ISSUE TITLE
[minio-service] handle POST file objects as IO stream, use put_object instead of fput_object

### ISSUE THREAD

**Issue by wallacerob** [Grainger-Engineering-Library/3deposit#55]

**Comment by rwwalla2** [comment]
`# Put a file with default content-type.
try:
    with open('my-testfile', 'rb') as file_data:
        file_stat = os.stat('my-testfile')
        client.put_object('my-bucketname', 'my-objectname',
                          file_data, file_stat.st_size)
except ResponseError as err:
    print(err)`
